### ISSUE TITLE
purescript-suggest tries to open the file <module> and fails

### ISSUE THREAD

**Issue by paf31** [nwolverson/purescript-suggest#13]
I can't quite figure out when this happens, but the only place that name appears in the compiler source is related to `Prim` modules, so maybe those warnings can just be ignored?

**Comment by paf31** [comment]
Apparently this is related to shadowed imports.

**Comment by nwolverson** [comment]
Literally the string `<module>`?

Happy to use this issue to investigate/narrow down the problem but I suspect if we're opening a wrong filename then that's because an error is output from the compiler JSON output that either shouldn't be or has the wrong file - so should be a fix in the compiler?

Unless the failure mode here is something that can be improved as well as fixing any underlying issue.

**Comment by nwolverson** [comment]
Managed to repro, this also makes `psa` fall over.  Compiler json output as follows, there is no suggestion given so really no reason we should be looking at those entries or fall over on them, I guess.

```json
{
      "position": {
        "startLine": 0,
        "startColumn": 0,
        "endLine": 0,
        "endColumn": 0
      },
      "message": "  Shadowed definitions are in scope for type Array from the following open imports:\n\n    import Prim\n\n  These will be ignored and the local declaration will be used.\n",
      "errorCode": "ScopeShadowing",
      "errorLink": "https://github.com/purescript/documentation/blob/master/errors/ScopeShadowing.md",
      "filename": "<module>",
      "moduleName": "Main",
      "suggestion": null,
      "allSpans": [
        {
          "start": [
            0,
            0
          ],
          "name": "<module>",
          "end": [
            0,
            0
          ]
        }
      ]
    },
    {
      "position": {
        "startLine": 0,
        "startColumn": 0,
        "endLine": 0,
        "endColumn": 0
      },
      "message": "  Shadowed definitions are in scope for type Array from the following open imports:\n\n    import Prim\n\n  These will be ignored and the local declaration will be used.\n",
      "errorCode": "ScopeShadowing",
      "errorLink": "https://github.com/purescript/documentation/blob/master/errors/ScopeShadowing.md",
      "filename": "<module>",
      "moduleName": "Main",
      "suggestion": null,
      "allSpans": [
        {
          "start": [
            0,
            0
          ],
          "name": "<module>",
          "end": [
            0,
            0
          ]
        }
      ]
    },
```

What's odd is that `purs` is complaining about the right module (rather than `Prim`) but the filename/source spans are junk.

**Comment by nwolverson** [comment]
Linked issue got fixed, closing.
